---
kind: Template
apiVersion: v1
metadata:
  name: oauth-sidecar-template
  annotations:
    openshift.io/display-name: Application With OpenShift OAuth Sidecar template
    description: Creates an application with traffic routed through an OpenShift OAuth Proxy sidecar
    iconClass: icon-openshift
    tags: instant-app
  labels:
    app: oauth-sidecar-template
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: proxy
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${NAME}"}}'
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    replicas: 1
    selector:
      name: "${NAME}"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: "${NAME}"
      spec:
        serviceAccountName: proxy
        containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: ${{PROXY_PORT}}
            protocol: TCP
          args:
          - "--https-address="
          - "--http-address=:${PROXY_PORT}"
          - "--provider=openshift"
          - "--openshift-service-account=proxy"
          - "--upstream=http://localhost:${APP_PORT}"
          - "--tls-cert=/etc/tls/private/tls.crt"
          - "--tls-key=/etc/tls/private/tls.key"
          - '--cookie-name=OCP_TOKEN'
          - '--cookie-expire=24h0m0s'
          - '--cookie-refresh=8h0m0s'
          - "--cookie-domain=.rht-labs.com"
          - "--cookie-name=OCP_TOKEN"
          - "--cookie-secret=${COOKIE_SECRET}"
        - name: "${NAME}"
          image: "${NAME}"
          imagePullPolicy: Always
          ports:
          - containerPort: ${{APP_PORT}}
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext:
          capabilities: {}
          privileged: false
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: "${NAME}"
      app: "${NAME}"
    name: "${NAME}"
  spec:
    ports:
    - port: ${{PROXY_PORT}}
      protocol: TCP
      targetPort: ${{PROXY_PORT}}
    selector:
      name: "${NAME}"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      name: "${NAME}"
      app: "${NAME}"
    name: "${NAME}"
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    port:
      targetPort: ${{PROXY_PORT}}
    to:
      kind: Service
      name: "${NAME}"
      weight: 100
    wildcardPolicy: None
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: oauth-test
- description: The port on which the proxied application listens on
  displayName: App Port
  name: APP_PORT
  value: "8080"
  required: true
- description: The port on which the proxy listens for incoming requests
  displayName: Proxy Port
  name: PROXY_PORT
  value: "8090"
  required: true
- description: OAuth Proxy Cookie Secret used to encrypt cookie contents
  displayName: Cookie Secret
  name: COOKIE_SECRET
  required: true
  generate: expression
  from: "[a-zA-Z0-9]{32}"
labels:
  template: oauth-sidecar-template
